name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Integration Test
        run: |
          chmod 755 service/*.sh
          docker-compose run -u root service /bin/sh -c "./wait-for-buckets.sh && ./wait-for-it.sh mssql:1433 -s -t 90 -- mvn clean test -Dtests=integration"
